### ISSUE TITLE
Masking doesn't allow for natural user input 

### ISSUE THREAD

**Issue by nijk** [nijk/react-duration-input-mask#17]
**Describe the bug**
Masking happens on each change event, this behaviour is frustrating if the user intends to add more than one change that forces masking, e.g. `6s` => `600s`,

**To Reproduce**
Steps to reproduce the behaviour:
1. Use `maskOnChange={true}` prop or ensure `maskOnChange` is not provided
2. Input any value that forces a change to masking: e.g. `6s` => `60s`
3. See value is masked to `1m`, the caret is at the end of the input and it is impossible to naturally add another `0` to create an input of `600s` which would be masked as `10m`

**Expected behaviour**
Perhaps the component shouldn't mask on each change event, rather it should invoke a timeout that masks only after an amount of time where there has been no change events. This timeout value should be configurable via props.

**Comment by j3tchy** [comment]
I've added a `maskDuration` prop which allows a user to set the timeout. We should discuss this update and I will move onto tests if we're happy with the update.
